### ISSUE TITLE
Add logic to handle -f for cmake builds

### ISSUE THREAD

**Issue by IgorTodorovskiIBM** [ZOSOpenTools/utils#103]
What do you want the -f option to do?  With the code as it is, cmake will run again but will probably skip writing any new option since the existing output still exists and the source hasn't changed.  The user may not get what they want.

This will be especially apparent with the build step.  Existing .o files will be there and make will skip recompiling them even though the -f option was specified.

_Originally posted by @perry-ca in https://github.com/ZOSOpenTools/utils/pull/102#discussion_r1014478460_

**Comment by perry-ca** [comment]
I was thinking that we can create a ZOPEN_CLEAN_CMD that the port can define to delete all of the build output.  Along with this new step, add a -c option that will clean up the build by running this command and then cleaning up any status files (eg. config.success).

The -f option then runs the clean up followed by a build.

**Comment by IgorTodorovskiIBM** [comment]
That sounds good to me!

**Comment by IgorTodorovskiIBM** [comment]
I'll close this since it's addressed in https://github.com/ZOSOpenTools/utils/pull/113. Thanks
