### ISSUE TITLE
Consistent naming conventions for common tooling / environment variables

### ISSUE THREAD

**Issue by MikeFultonDev** [ZOSOpenTools/utils#13]
**Updated Description based on discussion below:**
To avoid collisions in the globally scoped 'shell', we will:

 - Prefix environment variables with ZOPEN_, e.g. ZOPEN_GIT_URL
  - Prefix tools with `zopen-`, e.g. `zopen-build`

We will not use a suffix for our scripts (e.g. `zopen-build` instead of build.sh)

We will use the name `buildenv` instead of setenv.sh (we do not need to prefix a source'd file with zopen because we know exactly what directory the buildenv file is in) 

We will require that `zopen-build` be run from the root port directory by default, since it will look for `buildenv` in the current working directory. We will provide a -e option to specify an alternate `buildenv` file to be source'd if they need to override the standard build environment set up.

**Original:**

My preference is to avoid abbreviations whenever possible, how about .buildenv? 

Also minor, we don't have to address it here, but I had a similar concern with set portcrtenv.sh, where it took me some time to figure out that crt means create.

_Originally posted by @IgorTodorovskiIBM in https://github.com/ZOSOpenTools/utils/pull/12#discussion_r890299265_

**Comment by jshimoda9323** [comment]
I like .buildenv better than setenv.sh, because it's more clear that the script is for/related to build.sh.  I don't really like how it's a hidden file (the dot prefix) because IMHO you only want to hide files when they will 'get in the way' of 'ls' - in this case I think it is appropriate to see the file in normal 'ls' output.  (I realize the dot prefix is sometimes synonymous with sourcing an environment, but I don't think it should be).

As for portcrtenv.sh, I was initially thinking something like portCreateEnv.sh or port_create_env.sh, but I think the existing convention is generally more accepted, so i actually like portcrtenv.sh as it is.

**Comment by jshimoda9323** [comment]
Speaking of naming things here, do we want to choose a more descriptive name than build.sh?  Something like zotbuild.sh?  (Then we can rename the .buildenv file to .zotenv, which gives it a nice prefix.)

**Comment by MikeFultonDev** [comment]
@IgorTodorovskiIBM @perry-ca @ccw @agiorgio would be good to get more opinions here. 
@jshimoda9323 brings up some excellent points.

**Comment by MikeFultonDev** [comment]
When we update this, lets coordinate since Jenkins automation will presumably be affected and of course the externals will be hit. 
Another question - do we need the .sh? I like extensions in general but I'm also lazy. 

Of course, to be pendantic 'env' is an abbreviation but I don't think any of us want to write 'environment' every time.

Another consideration is consistency. For better or worse, the IBM compiler teams have gone with .env for setting up environments in the IBM Z and Cloud Modernization Stack.

**Comment by MikeFultonDev** [comment]
My opinions (loosely held):
- .buildenv : consistent with .env but 'different' so no collision
- I like zotbuild.sh (or maybe zotbuild)
- For consistency, portcreateenv.sh (or portcreateenv) would be good since a couple people didn't like 'crt'
- I would also go with portcheckenv.sh (or portcheck) for the reasons above

**Comment by MikeFultonDev** [comment]
Thinking some more - we should probably have a common prefix of either port or zot (or another prefix id someone has a better one). So I would say if we add a prefix to build it should likely be port. The other alternative (which I would be ok with) would be to change all the env vars and the current ‘port’ scripts to be ZOT_ and zot respectively.

**Comment by jshimoda9323** [comment]
On the .sh extension question, I'm of the opinion that we should remove it for two reasons:
1. The correct interpreter will be invoked via the #! on the first line of the script anyway, so telling users that this is a shell script via the .sh extension is not required.
2. If we re-code the script in another scripting language in the future, it can be easily replaced with no name change.

**Comment by IgorTodorovskiIBM** [comment]
> 2. If we re-code the script in another scripting language in the future, it can be easily replaced with no name change.

This is a good point, most linux script do not have the .sh extension either.  It's also recommended in the google style guide: https://google.github.io/styleguide/shellguide.html#s2.1-file-extensions

**Comment by jshimoda9323** [comment]
As for the prefix question, I personally like ZOT_ for environment variables and 'zot' for scripts because it's unique (I think? Does anyone know of other uses of 'zot'?).  The existing PORT_ and 'port' prefix reminds me too much of the freeBSD 'ports' collection.

**Comment by MikeFultonDev** [comment]
I actually like ZOT too :) ... 
Nothing too significant came up with a simple google... https://duckduckgo.com/?q=zot+&t=newext&atb=v243-1&ia=web

**Comment by MikeFultonDev** [comment]
Hm. I found this (which isn't good) but I don't know how common it is: https://www.waywordradio.org/zot/
Thumb up if you've heard of this definition. Thumb down if you haven't

**Comment by MikeFultonDev** [comment]
Around naming - i think it's important to talk about the full name of something (e.g. ZOSOpenTools repo or the z/OS Open Tools Initiative. But an acronym for a prefix seems pretty reasonable. 
I did find a software project called zot but it doesn't seem 'huge' (perhaps a Go SME might know?) 
https://pkg.go.dev/zotregistry.io/zot#section-readme

**Comment by IgorTodorovskiIBM** [comment]
I'm not a big fan of acronyms, but I think ZOT_ is fine.  ZOPEN_ is another alternative

**Comment by l-lindsay** [comment]
> Around naming - i think it's important to talk about the full name of something (e.g. ZOSOpenTools repo or the z/OS Open Tools Initiative. But an acronym for a prefix seems pretty reasonable. I did find a software project called zot but it doesn't seem 'huge' (perhaps a Go SME might know?) https://pkg.go.dev/zotregistry.io/zot#section-readme

Might be good to stay away from zot since it looks like that is being used for a larger initiative for OCI compliant container registry: https://zotregistry.io/

**Comment by ccw-1** [comment]
The purpose is to avoid name collision? it can be slightly longer. For example ZOPEN_

**Comment by MikeFultonDev** [comment]
Yes. To avoid name collision.

**Comment by MikeFultonDev** [comment]
so there seems to be 3 choices to have a 'reasonable' hope of avoiding name collisions:
- ZOT_xxx
- ZOPEN_xxx
- PORT_xxx

To me it seems reasonable to use the same prefix (without the underscore) in the scripts we run too, e.g.
[zot|zopen|port]build[.sh]

It also sounds like people are leaning toward NOT having a '.sh' extension since the `#!<...>` on the first line defines the language of the file (and lets us change to another language, or compiled code without changing the externals). 

How about a simple 'vote' for each possible name - thumb up for the 1 you like?

**Comment by MikeFultonDev** [comment]
zot

**Comment by MikeFultonDev** [comment]
zopen

**Comment by MikeFultonDev** [comment]
port

**Comment by MikeFultonDev** [comment]
@l-lindsay not sure how much it matters but I see that OCI zot registry is strictly amd64. Will we overlap?

**Comment by perry-ca** [comment]
On the extensions, we use .shinc for scripts that need to be sourced (i.e. run like `. buildenv.shinc`).

**Comment by MikeFultonDev** [comment]
Thumbs up if you want to KEEP the .sh extension

**Comment by MikeFultonDev** [comment]
Thumbs up if you want to DROP the .sh extension

**Comment by MikeFultonDev** [comment]
Thumbs up if you want the 'setenv.sh' file to now be called buildenv

**Comment by MikeFultonDev** [comment]
Thumbs up if you want the 'setenv.sh' file to now be called .buildenv (note the leading dot)

**Comment by MikeFultonDev** [comment]
@ccw-1 @IgorTodorovskiIBM @jshimoda9323 @perry-ca please vote for the next batch of choices...
Unless someone speaks up, we will rename the env vars to start with ZOPEN_ and we will rename the scripts to start with zopen

**Comment by MikeFultonDev** [comment]
Ok. So here is I believe the summary of what people that voted would like to see. 
To avoid collisions in the globally scoped 'shell', we will:
- Prefix environment variables with ZOPEN_, e.g. ZOPEN_GIT_URL 
- Prefix tools with zopen, e.g. zopenbuild

We will not use a suffix for our scripts (e.g. zopenbuild instead of build.sh)

We will use the name buildenv instead of setenv.sh (we do not need to prefix a source'd file with zopen because we know exactly what directory the buildenv file is in) [ or ... do we want zopenbuildenv for consistency? ]

We will require that zopenbuild be run from the root port directory by default, since it will look for _buildenv_ in the current working directory. We will provide a `-e` option to specify an alternate _buildenv_ file to be source'd if they need to override the standard build environment set up. 

@IgorTodorovskiIBM @jshimoda9323 Look ok (others feel free to add your thoughts)

**Comment by IgorTodorovskiIBM** [comment]
> Ok. So here is I believe the summary of what people that voted would like to see. To avoid collisions in the globally scoped 'shell', we will:
> 
> * Prefix environment variables with ZOPEN_, e.g. ZOPEN_GIT_URL
> * Prefix tools with zopen, e.g. zopenbuild
> 
> We will not use a suffix for our scripts (e.g. zopenbuild instead of build.sh)
> 
> We will use the name buildenv instead of setenv.sh (we do not need to prefix a source'd file with zopen because we know exactly what directory the buildenv file is in) [ or ... do we want zopenbuildenv for consistency? ]
> 
> We will require that zopenbuild be run from the root port directory by default, since it will look for _buildenv_ in the current working directory. We will provide a `-e` option to specify an alternate _buildenv_ file to be source'd if they need to override the standard build environment set up.
> 
> @IgorTodorovskiIBM @jshimoda9323 Look ok (others feel free to add your thoughts)

I'm good with that, I personally wouldn't mind adding a hyphen between zopen and the script name. (e.g. zopen-build).

In the future, it might be interesting if we create a driver script, named `zopen` which based on the first argument would call the appropriate zopen script, like zopenbuild.  For example, `zopen build` would call `zopenbuild`.  One benefit of this is that all functionality would be driven through one interface (including building, pulling the latest images into the bootstrap dir, etc...) and we could provide a help option to document all tools in one view (e.g. `zopen help`)

**Comment by jshimoda9323** [comment]
This all sounds good to me, and I like Igor's suggestions.

**Comment by ccw-1** [comment]
I am good with that.

**Comment by IgorTodorovskiIBM** [comment]
PR https://github.com/ZOSOpenTools/utils/pull/27 implements most of the ideas discussed here.

Unfortunately, `git mv build.sh zopen-build` fails to detect the rename so a proper diff is not shown.  Though, it did work for downloadports.

**Comment by IgorTodorovskiIBM** [comment]
Should we also change the default dependency search location to $HOME/zopen instead of $HOME/zot?

**Comment by ccw-1** [comment]
yes

**Comment by MikeFultonDev** [comment]
@IgorTodorovskiIBM ok to close? I think you've done what we need here?

**Comment by IgorTodorovskiIBM** [comment]
Yes, I'll close it off
