### ISSUE TITLE
Provide consistent wording for our initiative.

### ISSUE THREAD

**Issue by MikeFultonDev** [ZOSOpenTools/utils#15]
```suggestion
  echo "To see a fully functioning z/OS OpenTools sample port" >&2
```

_Originally posted by @IgorTodorovskiIBM in https://github.com/ZOSOpenTools/utils/pull/12#discussion_r890151750_

**Comment by MikeFultonDev** [comment]
Use z/OS Open Tools Initiative for the name of the initiative and ZOSOpenTools when referencing the 'id' that the repositories are grouped under.

**Comment by MikeFultonDev** [comment]
@IgorTodorovskiIBM i think you've done this?

**Comment by IgorTodorovskiIBM** [comment]
Yep, I dont see any more references to z/OS OpenTools
