### ISSUE TITLE
Should we add an option to prepend an additional path to search for dependencies?

### ISSUE THREAD

**Issue by IgorTodorovskiIBM** [ZOSOpenTools/utils#20]
Currently, build.sh searches these three paths for dependencies:
```
293     if [ -r "${HOME}/zot/prod/${dep}/.env" ]; then
294       depdir="${HOME}/zot/prod/${dep}"
295     elif [ -r "/usr/bin/zot/${dep}/.env" ]; then
296       depdir="/usr/bin/zot/${dep}"
297     elif [ -r "${HOME}/zot/boot/${dep}/.env" ]; then
298       depdir="${HOME}/zot/boot/${dep}"
```
It may be useful to prepend your own path via an option or environment variable for the following reasons:
* HOME dir may not have enough disk space. The workaround of creating a symlink is an added manual step and not obvious vs specifying the new search path as an option/env
* We may want to test our newly built tool as a dependency for the other open source projects, and having the ability to prepend a search path can be useful in this case.

**Comment by MikeFultonDev** [comment]
Is this still required @IgorTodorovskiIBM ? I know you did some work with Jenkins to use an alternate technique, but not sure if it's sufficient?

**Comment by IgorTodorovskiIBM** [comment]
I added an implementation for this under https://github.com/ZOSOpenTools/utils/pull/27 .  I will use this feature to enable testing of our "development" releases via Jenkins.
