### ISSUE TITLE
chtag of files that have a space not being properly tagged

### ISSUE THREAD

**Issue by MikeFultonDev** [ZOSOpenTools/utils#29]
after git clone, chtag is not working on files with special characters like spaces and tabs, e.g.
```
git/t/t4135/git-with tab.diff
```

and gives errors like:
```
chtag: FSUM6180 file "git/t/t4135/add-with": EDC5129I No such file or directory.
```

(this is in 'gitport' repo)

**Comment by dougburns** [comment]
perlport shows a similar issue.
The xargs command for chtag in applyPatches() doesn't include the file name at all, resulting in lots of:
```Usage: chtag -m | -t [-c codeset] [-hqRv] pathname...```
I'll have a go at fixing both of these up.

**Comment by dougburns** [comment]
The issue I was seeing with perlport is fixed in the latest level of utils, so I'm just addressing the original problem of filenames with spacs.
