### ISSUE TITLE
Change zopen-build so it deletes .git* files from inflated tarball build before setting up local .git repo

### ISSUE THREAD

**Issue by zopencommunity** [ZOSOpenTools/utils#40]
Most tarball builds do not have a .git* set of directories and files, but a few do (in particular xxhashport). We have a 'hack' in place to rename the .git directory but I'd like to change the logic to just DELETE .git and to also delete .gitattributes (and any other .git* file). The reasons are:
- I don't see any need to keep it around for the build and there should be no need to 'patch' any of these files
- It complicates the build logic

Any Objections? @IgorTodorovskiIBM @jshimoda9323 @fanbo-meng ?

**Comment by MikeFultonDev** [comment]
this is done now
