### ISSUE TITLE
zopen build error: unexpected text from xlclang -qversion

### ISSUE THREAD

**Issue by jshimoda9323** [ZOSOpenTools/utils#44]
Just did a pull from utils...now getting this error when trying to compile autoconf:
```
>ZOPEN_CHECK=skip ZOPEN_INSTALL=skip ../utils/bin/zopen build
Checking environment configuration...
***ERROR: xlclang compiler specified, but it is not a 'IBM C/C++ for Open Enterprise Languages on z/OS' compiler
```
.xlclang -qversion doesn't return what we are expecting in zopen-build:
```
12:05:15:zopen:/u/jshimod/zopen/dev/autoconfport>
>xlclang -qversion
        z/OS V2.3.1 XL C/C++
```
but zopen-build expects: `IBM C/C++ for Open Enterprise Languages on z/OS`

**Comment by MikeFultonDev** [comment]
@jshimoda9323 is this fixed? if so can you close it?

**Comment by jshimoda9323** [comment]
yes this one is fixed.
