### ISSUE TITLE
auto-home variable generation not working for directories with dots

### ISSUE THREAD

**Issue by MikeFultonDev** [ZOSOpenTools/utils#53]
For the libraries, each of them has a name that is similar to xxhashport. xxhashport has the following:

v0.8.1 is the name of the directory that is 'in' the tarball
xxHash-0.8.1 is created as a symbolic link to the v0.8.1 tarball

When the .env file is being generated, it is trying to use the v0.8.1 and is generating an invalid environment variable.
This causes subsequent use by things like 'rsync' to fail, e.g.

https://128.168.139.253:8443/job/Port-Build/287/console

Fix is probably to have some sort of env var that we can export to indicate the alias name (symbolic link) for the directory rather than the actual directory although there are likely other ways to tackle this.

**Comment by MikeFultonDev** [comment]
Currently, the 'numbered' tarballs are for xxhash, zstd, lz4

**Comment by IgorTodorovskiIBM** [comment]
How about specifying ZOPEN_NAME for the 'numbered' tarballs.  PR: https://github.com/ZOSOpenTools/utils/issues/53#event-7343081558

**Comment by MikeFultonDev** [comment]
@IgorTodorovskiIBM and @HarithaIBM is this fixed now? If so, can you close it?

**Comment by IgorTodorovskiIBM** [comment]
Fixed by specifying ZOPEN_NAME, closing off
