### ISSUE TITLE
Update zopen-importenvs to consider the standard zopen prod/boot/dev dirs

### ISSUE THREAD

**Issue by IgorTodorovskiIBM** [ZOSOpenTools/utils#56]
Currently zopen-importenvs only sources .envs from $HOME/zopen/boot.

```
. zopen-importenvs
```

It should also source from $HOME/zopen/prod or optionally, an argument specified directory.

See: https://github.com/ZOSOpenTools/utils/blob/main/bin/zopen-importenvs

**Comment by dougburns** [comment]
While getting my environment set up for the first time, I was thinking that we need something similar to this (and then found the existing issue).
Ideally, I think it would be good to be able to source multiple directories, avoiding duplication of tools that are in more than one.
e.g.
```. zopen-importenvs prod boot```
This should source everything from prod, and then everything from boot that hasn't already been found in prod.

If that sounds sensible, I'm happy to have a go at implementing it.

**Comment by IgorTodorovskiIBM** [comment]
@HarithaIBM is making some improvements to this as we speak. 

> This should source everything from prod, and then everything from boot that hasn't already been found in prod.

I agree, we should change the logic in zopen build as well such that the first one in the search order wins.
