### ISSUE TITLE
Add project licenses into the patches directory and enhance zopen generate to take OSS license as input

### ISSUE THREAD

**Issue by IgorTodorovskiIBM** [ZOSOpenTools/utils#67]
Question originally came from Doug Burns:
> Given that some licenses (GPL for a start) require derivative works to be licenses under the same terms as the primary work, shouldn't we be matching the licenses on the port repos to the ones for the upstream repo?

After discussing with legal, we should be providing the license from the original OSS repo

**Comment by IgorTodorovskiIBM** [comment]
zopen generate changes: https://github.com/ZOSOpenTools/utils/pull/68

**Comment by MikeFultonDev** [comment]
@IgorTodorovskiIBM is this done?

**Comment by IgorTodorovskiIBM** [comment]
Yes, closing
