### ISSUE TITLE
spaces in files causes 'git add' grief (gitport has these)

### ISSUE THREAD

**Issue by MikeFultonDev** [ZOSOpenTools/utils#77]
#73 fixes the ‘chtag’ for git, but it gets stuck a bit later when trying to do a ‘git add’. This is a 'new path' with the branch: https://github.com/ZOSOpenTools/gitport/tree/tarballbuild and specifying a tarball build (e.g. `export ZOPEN_TYPE="TARBALL"`)  

So a fix similar to #73 is required for tarball to build to get past:
```
fatal: pathspec './t/t4135/add-with' did not match any files
```
(the file names of add-with have a space after them before the rest).

Also note this is annoying because that message above is spat out in the wrong code page (git bug?)

**Comment by IgorTodorovskiIBM** [comment]
Can we close this now?
