### ISSUE TITLE
The Makefile is getting corrupted when zopen build -v is run second time on expatport

### ISSUE THREAD

**Issue by HarithaIBM** [ZOSOpenTools/utils#80]
Git clone the expatport.
Run zopen build -v --. Makefile is generated and it is untagged.
and without any changes , run the command "zopen build -v" again and the Makefile is corrupted now.

**Comment by IgorTodorovskiIBM** [comment]
I believe @MikeFultonDev's fix (https://github.com/ZOSOpenTools/utils/pull/89) fixes this
